//
// Created by Philippe VIENNE on 19/02/2016.
//

#ifndef SERVEURTCP_CONSTANTS_H
#define SERVEURTCP_CONSTANTS_H

#define REUSE_SOCKETS 1
#define SERVER_PORT 3456
#define CLIENT_PORT 1645

#endif //SERVEURTCP_CONSTANTS_H
